### ISSUE TITLE
Does it work in awesome 4.2?

### ISSUE THREAD

**Issue by sarg** [Elv13/collision#23] opened 2017-11-18 07:12 UTC
I have noticed that after upgrade to 4.2 my keybindings for collision stopped functioning. I have tested the module with default rc.lua without any success.

**Comment by Elv13** [comment] 2017-11-23 20:43
Hello. I just tried and it seems to work as expected for me. How did you install Awesome? What's your Lua and LGI version?

**Comment by sarg** [comment] 2017-11-24 05:45
```
❯ awesome --version
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2

❯ apt show awesome
Package: awesome
Version: 4.2-3
Priority: optional
Section: x11
Maintainer: Reiner Herrmann <reiner@reiner-h.de>
Installed-Size: 2,716 kB
Provides: notification-daemon, x-window-manager
Depends: default-dbus-session-bus | dbus-session-bus, gir1.2-freedesktop, gir1.2-pango-1.0, lua-lgi (>= 0.9.2), menu, libc6 (>= 2.14), libcairo2 (>= 1.12.0), libdbus-1-3 (>= 1.9.14), libgdk-pixbuf2.0-0 (>= 2.22.0), libglib2.0-0 (>= 2.30.0), liblua5.3-0, libstartup-notification0 (>= 0.10), libx11-6, libxcb-cursor0 (>= 0.0.99), libxcb-icccm4 (>= 0.4.1), libxcb-keysyms1 (>= 0.4.0), libxcb-randr0 (>= 1.12), libxcb-render0, libxcb-shape0, libxcb-util0 (>= 0.3.8), libxcb-xinerama0, libxcb-xkb1, libxcb-xrm0 (>= 0.0.0), libxcb-xtest0, libxcb1 (>= 1.6), libxdg-basedir1, libxkbcommon-x11-0 (>= 0.5.0), libxkbcommon0 (>= 0.5.0)
```

**Comment by sarg** [comment] 2017-11-24 06:00
I have done everything from scratch. New user, default config. It didn't help. I can see collision bindings in awesome help window, but when I press key combinations they go to the focused applications. Every other key binding in awesome works as expected.

**Comment by Elv13** [comment] 2017-11-24 06:03
Did you recently update from Lua 5.1 to 5.3? I know Debian did.

Also what exactly happens when you press the collision keybindings. Any error?

**Comment by sarg** [comment] 2017-11-24 08:11
Yes, you could see liblua5.3-0 in Depends. 
When I press collision keybindings they go straight to the currently focused application. 
Xev, for example, shows which key where pressed.

```
KeyRelease event, serial 34, synthetic NO, window 0x1c00001,
    root 0x129, subw 0x1c00002, time 59486455, (24,35), root:(824,494),
    state 0x40, keycode 46 (keysym 0x6c, l), same_screen YES,
    XLookupString gives 1 bytes: (6c) "l"
    XFilterEvent returns: False
```

When I press awesome bindings, xev doesn't show them, because they are catched earlier.

**Comment by Elv13** [comment] 2017-11-24 19:43
> Yes, you could see liblua5.3-0 in Depends.

My question was: did you upgrade from Lua 5.1 to Lua 5.3 at the same time you upgraded Awesome.

I installed Lua 5.3 in a VM (I use Luajit, it's faster) and could reproduce the issue. So the problem wasn't Awesome 4.2, it was upgrading to Lua 5.3, which is slightly incompatible with 5.1. I pushed a fix.

**Closed by Elv13** 2017-11-24 19:43 UTC

**Comment by sarg** [comment] 2017-11-24 20:56
Thanks a lot. It works!
btw, I don't have lua binary, only liblua.
